### ISSUE TITLE
Не считывает русский язык

### ISSUE THREAD

**Issue by ElenVM** [EvGe22/ChatApp#1]
Шаги по воспроизведению проблемы:
1. Запустить ChatApp.
2. Ввести локальный ник. Нажать Apply. Нажать Connect.
3. Ввести сообщение на кириллице.

Ожидаемый результат:
Возвращает сообщение, которое мы ввели ни кириллице.

Фактический результат:
Непонятный набор символов.

**Comment by EvGe22** [comment]
Это очень странный баг. Я тесттил это с другом из другого города. У него пишется абра-кадарба, мне приходит всё нормально и отправляет на русском нормально. Потом проверяем логи(историю). Сообщения, введенные им всё еще абракадабра, а вот полученные от меня в логах в кодировке UTF-8 отображаются абсолютно корректно. Я честно без понятия, как это фиксить.

**Comment by dimalit** [comment]
А результат не меняетя в зависимости от того, кто кому звонил?

**Comment by EvGe22** [comment]
У него IP динамический, я к нему не могу дозвониться. Обход еще не работает, и скорее всего до завтра и не будет. Сегодня еще попробуем
