### ISSUE TITLE
Не устанавливается стандартный ник

### ISSUE THREAD

**Issue by ipehov** [EvGe22/ChatApp#10]
Шаги по воспроизведению проблемы:
1. Запустить программу.
2. Ввести ник. Нажать Apply.
3. Подключиться.
4. Пообщаться с другим пользователем
5. Нажать Disconect
6. Стереть ник и нажать Apply с пустым полем в нике
7. Подключиться

Ожидаемый результат:
Устанавливается стандартный ник для пользователей, которых не вводили ник (unnamed у вас по моему) 

Фактический результат:
Пустой ник

**Comment by EvGe22** [comment]
Если хотите сбросить ник - ручками вводите default. Сейчас уже при попытке ввести пустой ник вам скажет, что нельзя так делать.
