### ISSUE TITLE
Зависает программа

### ISSUE THREAD

**Issue by ElenVM** [EvGe22/ChatApp#12]
Шаги по воспроизведению проблемы:
1. Запустить ChatApp.
2. Ввести имя латинскими буквами в поле login.
3. В поле remote addres прописать адрес 127.0.0.1 (подключение самому к себе).
4. Высвечивает окно, что абонент занят.
5. Программа зависает.

Ожидаемый результат:
Возможность подключится к другому абоненту, либо выключить программу.

Фактический результат:
Программа не отвечает.

**Comment by EvGe22** [comment]
У меня такой проблемы не возникает. Всё работает адекватно. Ну и в любом случае - в чём смысл подключаться к самому себе, кроме как для тестирования программы? В реальном использовании такого не будет.
