### ISSUE TITLE
Окно программы не корректируется

### ISSUE THREAD

**Issue by romashkorylezzz** [EvGe22/ChatApp#14]
Действия.
1. Запускаем программу 

Ожидание.
Окно с возможностью изменения размера 

Результат.
![image](https://cloud.githubusercontent.com/assets/15571484/11664138/ac9e54d4-9de8-11e5-9b88-635eaf34e0e9.png) Окно не корректируется и на моем нэтбуке даже полностью на помещается

**Comment by romashkorylezzz** [comment]
И почему мой комментарий закрыт?

**Comment by EvGe22** [comment]
Потому что Артём изначально не захотел делать окно с изменяемым размером, потому что он не умеет. А мне влом. Так что это не планировалось. Значит не баг, а фича. :D
