### ISSUE TITLE
При запуске программы сразу же появляется сообщение - ошибка "Failed to connect to main server."

### ISSUE THREAD

**Issue by DimaKovalchuk** [EvGe22/ChatApp#17]
Шаги по воспроизведению проблемы:
1. Запускаю программу 
2. Хотел ввести ник

Ожидаемый результат:
Ввел ник

Фактический результат:
Сразу же появляется сообщение - ошибка "Failed to connect to main server."

**Comment by EvGe22** [comment]
Это, конечно, всё очень хорошо. Проблема в том, что в jar-ник не заложился драйвер MySQL. И  это релиз двухнедельной давности. Сейчас чат вообще переделывается. Так что я закрываю Issues на совсем, до выпуска новой рабочей версии.
