### ISSUE TITLE
Анонимное общение.

### ISSUE THREAD

**Issue by Sanches007** [EvGe22/ChatApp#5]
Шаги по воспроизведению проблемы:
1. Запустить ChatApp.
2. Убрать с поля ник все символы. Нажать Apply
3. Ввести ip и нажать Connect.
4. Ожидание подключения
5. Писать сообщение и отправлять.

Ожидаемый результат:
Оповещение что ник не введен.

Фактический результат:
Программа пытается общаться.

**Comment by koha26** [comment]
Читай ТЗ.
