### ISSUE TITLE
Некорректное поведение программы при подключении к программе НЕ ChatApp2015

### ISSUE THREAD

**Issue by TkachenkoMax** [EvGe22/ChatApp#7]
Шаги по воспроизведению проблемы: 
1. Запустить программу
2. Подключиться к chatapp2015 приложению
3. Отключиться, неважно пообщавшись или нет
4. Попытаться подключиться к не chatapp2015 приложению, например google.com

Ожидаемый результат:
Если сделать подключение к условному гуглу сразу при запуске чата будет логичное сообщение failed to connect, при нажатии ок можно ввести новый айпишник, все ок. При проделанных выше действиях появляется другой результат

Фактический результат:

Появляется сообщение в истор
![-1](https://cloud.githubusercontent.com/assets/15245651/11430311/357e0f2a-948d-11e5-8079-7128623758c3.jpg)
ии сообщений "connected to null", кнопка connect блокируется, disconnect разблокируется - складывается впечатление что произошло соединение (см. скрин)

**Comment by EvGe22** [comment]
Хмм, посмотрим.

**Comment by EvGe22** [comment]
Попробовал сделать так же - у меня программа виснет не на долго, но потом выдает, что "Failed to connect" всё же. Странно.
